<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700;800&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<style>
  :root { --ink:#122033; --muted:#667085; --paper:#f7f8fc; --line:#e7eaf1; --brand:#4f46e5; --accent:#f97360; --surface:#fff; }
  * { box-sizing:border-box; } body { background:var(--paper); color:var(--ink); font-family:'DM Sans',sans-serif; font-size:16px; line-height:1.65; } a { color:inherit; text-decoration:none; transition:.2s ease; } a:hover { color:var(--brand); text-decoration:none; }.site-shell{overflow:hidden}
  .site-header{background:rgba(255,255,255,.94);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:100;backdrop-filter:blur(16px)}.header-inner{max-width:1220px;margin:auto;min-height:76px;display:flex;align-items:center;gap:30px;padding:0 20px}.brand{color:var(--ink)!important;font-family:'Playfair Display',serif;font-weight:800;font-size:1.7rem;letter-spacing:-.06em;white-space:nowrap}.brand-mark{color:var(--brand)}.brand-dot{color:var(--accent)}.main-nav{display:flex;gap:22px;align-items:center;flex:1}.main-nav a{font-size:.9rem;font-weight:700;color:#475467}.main-nav a.active,.main-nav a:hover{color:var(--brand)}.search-form{display:flex;align-items:center;border:1px solid var(--line);border-radius:99px;padding:3px 5px 3px 14px;background:#fff;width:230px}.search-form input{border:0;outline:0;width:100%;background:transparent;font-size:.85rem}.search-form button{border:0;border-radius:50%;width:32px;height:32px;background:var(--brand);color:#fff}.mobile-toggle{display:none;border:0;background:transparent;font-size:1.2rem;color:var(--ink)}
  .page-wrap{max-width:1220px;margin:0 auto;padding:38px 20px 0}.content-grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:42px}.eyebrow,.article-category{color:var(--brand);font-size:.73rem;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.section-heading{font-family:'Playfair Display',serif;font-size:1.65rem;letter-spacing:-.04em;margin:0 0 20px}.section-heading:after{content:'';display:block;background:var(--accent);width:42px;height:3px;margin-top:10px}
  .hero{min-height:490px;border-radius:24px;overflow:hidden;display:flex;align-items:end;position:relative;padding:42px;background:#1e293b center/cover;color:#fff;margin-bottom:44px}.hero:before,.story-card .story-image:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 20%,rgba(10,18,34,.84))}.hero>*{position:relative;z-index:1}.hero-content{max-width:720px}.hero h1{font:800 clamp(2.15rem,5vw,4.4rem)/1.03 'Playfair Display',serif;letter-spacing:-.055em;margin:12px 0 18px}.hero-meta,.story-meta{font-size:.82rem;color:#dce2ec;display:flex;gap:15px;align-items:center}.hero-category{display:inline-flex;background:var(--accent);color:#fff;padding:6px 11px;border-radius:99px;font-size:.7rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}
  .story-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.story-card{background:var(--surface);border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:0 8px 24px rgba(16,24,40,.04);height:100%;display:flex;flex-direction:column}.story-image{height:220px;position:relative;display:block;overflow:hidden}.story-image img{width:100%;height:100%;object-fit:cover;transition:transform .45s ease}.story-card:hover .story-image img{transform:scale(1.06)}.story-body{padding:22px;display:flex;flex:1;flex-direction:column}.story-card h2{font:700 1.24rem/1.25 'Playfair Display',serif;letter-spacing:-.03em;margin:9px 0 11px}.story-card p{color:var(--muted);font-size:.92rem;margin:0}.story-foot{display:flex;justify-content:space-between;align-items:center;margin-top:auto;padding-top:18px;color:var(--muted);font-size:.78rem}
  .sidebar-panel{background:#fff;border:1px solid var(--line);border-radius:18px;padding:24px;margin-bottom:24px}.side-story{display:grid;grid-template-columns:76px 1fr;gap:13px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line)}.side-story:last-child{border-bottom:0;padding-bottom:0}.side-story img{width:76px;height:65px;object-fit:cover;border-radius:10px}.side-story h3{font:700 .9rem/1.25 'DM Sans',sans-serif;margin:4px 0 0}.tag-cloud{display:flex;flex-wrap:wrap;gap:8px}.tag-cloud a{font-size:.78rem;padding:6px 10px;border-radius:99px;background:#f1f0ff;color:var(--brand);font-weight:700}
  .article-page,.form-card{background:#fff;border:1px solid var(--line);border-radius:20px;overflow:hidden}.article-cover{width:100%;height:400px;object-fit:cover}.article-copy{padding:34px}.article-copy h1{font:800 clamp(2rem,4vw,3.4rem)/1.1 'Playfair Display',serif;letter-spacing:-.05em;margin:12px 0 20px}.article-copy p{font-size:1.06rem;color:#475467;white-space:pre-line}.article-byline{border-top:1px solid var(--line);padding-top:18px;margin-top:28px;display:flex;justify-content:space-between;color:var(--muted);font-size:.85rem}.form-card{padding:32px}.form-card label{font-weight:700;font-size:.87rem}.form-control{border:1px solid #d6dae4!important;border-radius:10px!important;padding:.75rem .9rem!important;min-height:48px}.form-control:focus{box-shadow:0 0 0 3px rgba(79,70,229,.12)!important;border-color:var(--brand)!important}.btn-brand{background:var(--brand);border:0;border-radius:10px;color:#fff;font-weight:700;padding:12px 20px}.btn-brand:hover{background:#3730a3;color:#fff}.empty-state{padding:40px;text-align:center;background:#fff;border:1px dashed #cdd3df;border-radius:18px;color:var(--muted)}
  .site-footer{background:#122033;color:#c8d0df;margin-top:70px}.footer-inner{max-width:1220px;margin:auto;padding:48px 20px 25px;display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:40px}.site-footer h3{font:700 1rem 'DM Sans',sans-serif;color:#fff;margin-bottom:14px}.site-footer a{color:#c8d0df}.footer-brand{color:#fff!important}.social-links{display:flex;gap:9px}.social-links a{display:grid;place-items:center;width:35px;height:35px;border:1px solid #425168;border-radius:50%}.footer-bottom{border-top:1px solid #28394d;padding:18px 20px;text-align:center;font-size:.82rem}.notice{border-radius:10px;border:0}.back-to-top{position:fixed;bottom:20px;right:20px;border-radius:50%;width:42px;height:42px;display:grid;place-items:center;background:var(--brand)!important;color:#fff!important;border:0;z-index:10}
  @media(max-width:991px){.content-grid{grid-template-columns:1fr}.sidebar{display:none}.header-inner{min-height:64px}.mobile-toggle{display:block;margin-left:auto}.main-nav{display:none;position:absolute;top:64px;left:0;right:0;flex-direction:column;align-items:stretch;padding:18px 20px;background:#fff;border-bottom:1px solid var(--line)}.main-nav.show{display:flex}.search-form{width:100%}.hero{min-height:400px;padding:28px}.footer-inner{grid-template-columns:1fr 1fr}.page-wrap{padding-top:28px}}@media(max-width:600px){.story-grid{grid-template-columns:1fr}.hero{min-height:360px;border-radius:16px}.hero h1{font-size:2.35rem}.article-cover{height:250px}.article-copy,.form-card{padding:22px}.footer-inner{grid-template-columns:1fr}.article-byline{display:block}.article-byline span{display:block;margin-top:6px}}
</style>
